inhibit_all_warnings!

platform :ios, '9.0'

target 'ZTBase_Example' do
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'KMNavigationBarTransition'
  pod 'DZNEmptyDataSet'
  pod 'ZTBase', :path => '../'
end
